apiVersion: v1
kind: Service
metadata:
  name: nginx-np
  labels:
    purpose: service-np-demo
spec:
  type: NodePort
  selector:
    purpose: service-np-demo
    project: roboshop 
    environment: dev
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
       

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-np
  labels:
    purpose: service-np-demo
    project: roboshop
    environment: dev
spec:
  containers:
  - name: nginx
    image: nginx
    