apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
  labels:
    purpose: service-lb-demo
spec:
  type: LoadBalancer
  selector:
    purpose: service-lb-demo
    project: roboshop
    environment: dev
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
       

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-lb
  labels:
    purpose: service-lb-demo
    project: roboshop
    environment: dev
spec:
  containers:
  - name: nginx
    image: nginx
    